#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""FMTK quickstart

NOTE:  THIS TOOL IS IN VERY EARLY PROTOTYPE STAGE.
IT DOES NOT YET PRODUCE A FULL BUILD ENVIRONMENT.
"""

from os.path import dirname, abspath, normpath, isdir
from os.path import join as ospjoin
import sys

if __name__ == '__main__':

    pgmdir = dirname(__file__)
    lib_qs = normpath(abspath(ospjoin(pgmdir, 'lib', 'quickstart')))
    if isdir(lib_qs):
        sys.path.insert(1, dirname(lib_qs))

    from quickstart import fmtk

    try:
        result = fmtk.quickstart(sys.argv)
    except Exception as exc:
        print (exc)
        if hasattr(exc, 'args') and type(exc.args[0]) is int:
            result = int(exc.args[0])
        else:
            result = 63

    sys.exit(result)
